name: pass_the_pigs
description: Pass the Pigs
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.5.0-0 <4.0.0"

dependencies:
  bloc: ^8.1.1
  confetti: ^0.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  google_fonts: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_launcher_icons: ^0.14.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true
  assets:
    - assets/images/icons/dot.gif
    - assets/images/icons/no_dot.gif
    - assets/images/icons/leaningjowler.gif
    - assets/images/icons/oinker.gif
    - assets/images/icons/razorback.gif
    - assets/images/icons/snouter.gif
    - assets/images/icons/trotter.gif
    - assets/google_fonts/
