name: pass_the_pigs
description: Pass the Pigs
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  # flutter: ^3.0.5

dependencies:
  basic_utils: ^4.2.1
  bloc: ^8.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_platform_widgets: ^2.0.0
  google_fonts: ^3.0.1
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.5
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true
  assets:
    - assets/images/icons/dot.gif
    - assets/images/icons/no_dot.gif
    - assets/images/icons/leaningjowler.gif
    - assets/images/icons/oinker.gif
    - assets/images/icons/razorback.gif
    - assets/images/icons/snouter.gif
    - assets/images/icons/trotter.gif
