name: pass_the_pigs
description: Pass the Pigs
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.2-0 <3.0.0"

dependencies:
  basic_utils: ^4.5.2
  bloc: ^8.0.3
  confetti: ^0.7.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_platform_widgets: ^3.0.0
  google_fonts: ^4.0.3
  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.6
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true
  assets:
    - assets/images/icons/dot.gif
    - assets/images/icons/no_dot.gif
    - assets/images/icons/leaningjowler.gif
    - assets/images/icons/oinker.gif
    - assets/images/icons/razorback.gif
    - assets/images/icons/snouter.gif
    - assets/images/icons/trotter.gif
